#:schema ./.aviutl2-cli/aviutl2.schema.json
# 設定ファイルについては https://github.com/sevenc-nanashi/aviutl2-cli を参照してください。

[project]
id = "sevenc-nanashi.ported_tim"
name = "ported_tim"
version = "0.1.0"

[build_group]
aulua = "aulua build"

[development]
aviutl2_version = "latest"

[artifacts.tim2-mod2]
destination = "Script/tim2.mod2"

[artifacts.tim2-mod2.profiles.debug]
build = "cargo build"
source = "target/debug/ported_tim.dll"

[artifacts.tim2-mod2.profiles.release]
build = "cargo build --release"
source = "target/release/ported_tim.dll"

[artifacts.tim2_anm2]
build = { group = "aulua" }
source = "build/tim2.anm2"
destination = "Script/@tim.anm2.anm2"

[artifacts.tim2_obj2]
build = { group = "aulua" }
source = "build/tim2.obj2"
destination = "Script/@tim.obj2.obj2"

[artifacts.tim2_tra2]
build = { group = "aulua" }
source = "build/tim2.tra2"
destination = "Script/@tim.tra2.tra2"

[artifacts.tim2_cam2]
build = { group = "aulua" }
source = "build/tim2.cam2"
destination = "Script/@tim.cam2.cam2"

[artifacts.tim2_scn2]
build = { group = "aulua" }
source = "build/tim2.scn2"
destination = "Script/@tim.scn2.scn2"
