[tools]
bun = "latest"
"github:karoterra/aviutl2-aulua" = "0.6.0"
"github:sevenc-nanashi/aviutl2-cli" = { version = "0.8.0-preview.0", bin = "au2.exe" }
"npm:rulesync" = "latest"
ruby = "latest"
stylua = "latest"

[settings]
npm = { package_manager = "bun" }

[tasks.build]
run = ["aulua build"]

[tasks.dev]
run = ["mise watch -w aulua.yaml -w Rakefile -w lua -e yaml,lua,hlsl build"]
