[plugins]
cargo-prebuilt = "https://github.com/sevenc-nanashi/mise-cargo-prebuilt"

[tools]
bun = "latest"
"github:karoterra/aviutl2-aulua" = "latest"
"github:sevenc-nanashi/aviutl2-cli" = { version = "latest", bin = "au2.exe" }
"npm:rulesync" = "latest"
ruby = "latest"
stylua = "latest"
"cargo-prebuilt:cargo-edit" = "latest"
"github:EmbarkStudios/cargo-about" = "latest"

[settings]
npm = { package_manager = "bun" }

[tasks.build]
run = ["aulua build", "rake i18n:build"]

[tasks.dev]
run = ["mise watch -w aulua.yaml -w Rakefile -w lua -e yaml,lua,hlsl build"]
